name: Sync Fork and Merge Custom Content

on:
  schedule:
    # 每天UTC时间21:00运行，这相当于北京时间凌晨5:00 (UTC+8)
    - cron: '0 21 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  sync-and-merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout your fork
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Add upstream remote
      run: git remote add upstream https://github.com/zwc456baby/iptv_alive.git

    - name: Fetch upstream changes
      run: |
        git fetch upstream
        git fetch origin
        git branch -a

    - name: Determine current branch
      run: |
        CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
        echo "Current branch is $CURRENT_BRANCH"
        echo "CURRENT_BRANCH=$CURRENT_BRANCH" >> $GITHUB_ENV

    - name: Sync with upstream
      run: |
        UPSTREAM_BRANCH=$(git branch -r | grep upstream/main || git branch -r | grep upstream/master)
        if [ -z "$UPSTREAM_BRANCH" ]; then
          echo "Could not find upstream/main or upstream/master branch"
          git branch -r
          exit 1
        fi
        UPSTREAM_BRANCH=${UPSTREAM_BRANCH##*/}
        echo "Upstream branch is $UPSTREAM_BRANCH"
        
        if git merge upstream/$UPSTREAM_BRANCH --allow-unrelated-histories -X theirs; then
          echo "Merged successfully"
        else
          echo "Merge failed, trying to pull instead"
          git pull upstream $UPSTREAM_BRANCH --allow-unrelated-histories -X theirs
        fi

    - name: Merge live.txt and live_custom.txt
      run: |
        if [ -f live.txt ] && [ -f live_custom.txt ]; then
          # 将live.txt的内容复制到live_all.txt
          cat live.txt > live_all.txt
          
          # 将live_custom.txt中不在live.txt中的行追加到live_all.txt
          grep -vxFf live.txt live_custom.txt >> live_all.txt
        elif [ -f live.txt ]; then
          cp live.txt live_all.txt
        elif [ -f live_custom.txt ]; then
          cp live_custom.txt live_all.txt
        else
          echo "Neither live.txt nor live_custom.txt found."
          exit 1
        fi

    - name: Commit and push changes
      run: |
        git add live_all.txt
        git commit -m "Sync with upstream and merge custom content" || echo "No changes to commit"
        git push origin ${{ env.CURRENT_BRANCH }}
